#!/bin/bash

# Helper Functions
function turn_to() {
    # Turn to a position, accommodate coupling backlash, center and park.
    position=$1 # Parameter, in degrees.
    backlash_angle=8 # degrees
    lowpos=$((  position - $backlash_angle ))
    highpos=$(( position + $backlash_angle ))

    ./angle $lowpos
    sleep 0.75
    ./angle $highpos
    sleep 0.25
    ./angle $position
    sleep 0.1
}

function park_at_midpoint() {
    # Park servo at midpoint and stop driving PWM (so the servo "relaxes")
    turn_to 0
    ./sleep_mode
}

trap park_at_midpoint EXIT

# Main Flow
./init

while :; do
    for a in -90 90 45 0; do
	sleep 3
	echo -n "$a, "
	turn_to $a
    done
    echo done
    sleep 10
done
